# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema_roundtrip.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16schema_roundtrip.proto\"4\n\nFlightCode\x12\x0f\n\x07\x61irline\x18\x01 \x01(\t\x12\x15\n\rflight_number\x18\x02 \x01(\t\"W\n\rRoundTripData\x12#\n\x0eoutbound_codes\x18\x01 \x03(\x0b\x32\x0b.FlightCode\x12!\n\x0creturn_codes\x18\x02 \x03(\x0b\x32\x0b.FlightCodeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_roundtrip_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLIGHTCODE._serialized_start=26
  _FLIGHTCODE._serialized_end=78
  _ROUNDTRIPDATA._serialized_start=80
  _ROUNDTRIPDATA._serialized_end=167
# @@protoc_insertion_point(module_scope)
