# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema_roundtrip.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16schema_roundtrip.proto\"q\n\x0fRoundTripFlight\x12\x14\n\x0c\x66rom_airport\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x12\n\nto_airport\x18\x03 \x01(\t\x12\x0f\n\x07\x61irline\x18\x05 \x01(\t\x12\x15\n\rflight_number\x18\x06 \x01(\t\"$\n\x14RoundTripAirportCode\x12\x0c\n\x04path\x18\x02 \x01(\t\"\x9e\x01\n\x13RoundTripFlightData\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12!\n\x07\x66lights\x18\x04 \x03(\x0b\x32\x10.RoundTripFlight\x12+\n\x0c\x61irport_from\x18\r \x01(\x0b\x32\x15.RoundTripAirportCode\x12)\n\nairport_to\x18\x0e \x01(\x0b\x32\x15.RoundTripAirportCode\"\xa0\x01\n\rRoundTripData\x12*\n\x0c\x66lights_data\x18\x03 \x03(\x0b\x32\x14.RoundTripFlightData\x12\'\n\npassengers\x18\x08 \x03(\x0e\x32\x13.RoundTripPassenger\x12\x1c\n\x04seat\x18\t \x01(\x0e\x32\x0e.RoundTripSeat\x12\x1c\n\x04trip\x18\x13 \x01(\x0e\x32\x0e.RoundTripType*k\n\rRoundTripSeat\x12\x13\n\x0fUNKNOWN_RT_SEAT\x10\x00\x12\x0e\n\nRT_ECONOMY\x10\x01\x12\x16\n\x12RT_PREMIUM_ECONOMY\x10\x02\x12\x0f\n\x0bRT_BUSINESS\x10\x03\x12\x0c\n\x08RT_FIRST\x10\x04*Z\n\rRoundTripType\x12\x13\n\x0fUNKNOWN_RT_TRIP\x10\x00\x12\x11\n\rRT_ROUND_TRIP\x10\x01\x12\x0e\n\nRT_ONE_WAY\x10\x02\x12\x11\n\rRT_MULTI_CITY\x10\x03*w\n\x12RoundTripPassenger\x12\x18\n\x14UNKNOWN_RT_PASSENGER\x10\x00\x12\x0c\n\x08RT_ADULT\x10\x01\x12\x0c\n\x08RT_CHILD\x10\x02\x12\x15\n\x11RT_INFANT_IN_SEAT\x10\x03\x12\x14\n\x10RT_INFANT_ON_LAP\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_roundtrip_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROUNDTRIPSEAT._serialized_start=503
  _ROUNDTRIPSEAT._serialized_end=610
  _ROUNDTRIPTYPE._serialized_start=612
  _ROUNDTRIPTYPE._serialized_end=702
  _ROUNDTRIPPASSENGER._serialized_start=704
  _ROUNDTRIPPASSENGER._serialized_end=823
  _ROUNDTRIPFLIGHT._serialized_start=26
  _ROUNDTRIPFLIGHT._serialized_end=139
  _ROUNDTRIPAIRPORTCODE._serialized_start=141
  _ROUNDTRIPAIRPORTCODE._serialized_end=177
  _ROUNDTRIPFLIGHTDATA._serialized_start=180
  _ROUNDTRIPFLIGHTDATA._serialized_end=338
  _ROUNDTRIPDATA._serialized_start=341
  _ROUNDTRIPDATA._serialized_end=501
# @@protoc_insertion_point(module_scope)
